### ISSUE TITLE
logdna-agent crashing because of restart request

### ISSUE THREAD

**Issue by syphernl** [logdna/logdna-agent#35]
With the recent logdna-agent version on Ubuntu 16.04 I noticed it sometimes suddenly just dies off. The logs claim an agent restart was requested, yet this was not the case (or is something in the logdna-agent triggering this?)

```
[180119 10:06:00] Connected to logs.logdna.com:443 (52.168.140.197) (SSL)
[180119 10:06:00] Streaming /var/log/php7.0-fpm.log: 1 file(s)
[180119 10:07:09] Streaming /var/log/php7.0-fpm.log: 1 file(s)
[180119 10:07:28] Streaming /srv/http/**/logs/*_error.log: 16 file(s)
[180119 10:12:11] Agent restart request received, restarting...
Not stopped; may still be shutting down or shutdown may have failed
```

A simple `sudo service logdna-agent restart` doesn't bring it back up. This requires a `sudo service logdna-agent stop; sudo service logdna-agent start` to get it back online.

**Comment by leeliu** [comment]
What version are you running? We have fixed a couple of potential crash issues in more recent versions. Also on Ubuntu/Debian systems, I've found it more reliable to use `sudo /etc/init.d/logdna-agent restart`. Though it is strange with the stop/start, the restart just does both in code.

**Comment by syphernl** [comment]
We're on `1.4.12` on our testing environments. Strangely, this only seems to occur on our QA environment and not for Acceptance. And only on two particular servers with the same role.

**Comment by syphernl** [comment]
@leeliu This is still occurring with `1.4.12` unfortunately.

**Comment by leeliu** [comment]
It's hard to debug this w/o more info about your account and GitHub doesn't allow us to authenticate who you are. Can you reach out via the Help button at top right and click on Contact Support?

Your agents are using more ram than normal and # of events/s definitely will play a role in that. I suspect it's not all servers but just a couple. Anyway mention my name in the support request and I can follow up with you there.
